### ISSUE TITLE
训练过程中出现错误An error occurred during the training process

### ISSUE THREAD

**Issue by kongbai-account** [XuJiacong/PIDNet#65]
有人遇到这个问题吗，我用cityscapes就能训练完毕，但用自己的数据集就报这个错误
Has anyone encountered this problem? I can train with cityscapes, but this error is reported using my own dataset
![image](https://github.com/XuJiacong/PIDNet/assets/63712094/731dacd2-d785-4f38-80f9-50b048d51a4a)

**Comment by lpetflo** [comment]
I also encounter this error when trying to use PIDNet with my own binary segmentation dataset.
According to @tomihisaw in Issue #14 it might be an option to change the code in the criterion.py file (as well as propably some code in the utils.py file - @QiaoShin)
Issue #42 mentions this problem as well and it might as well be solved by changing the BASE_SIZE (therefore altering multiscale computation). However I can't validate this second approach.

For me changing the code in utils.py worked:
```
try:
    min_value = pred[min(self.min_kept, pred.numel() - 1)]
    threshold = max(min_value, self.thresh)
except:
    try:
        print("Using alternative loss from threshold")
        threshold = self.thresh
    except:
        print("===== ! ATTENTION ERROR OCCURED ! =====")
```
The second except wasn't used during my last 50 epoch run, so it seems to work fine this way. However valid_loss calculation won't work in cases where the alternative threshold get's used.
I also want to suggest, that reducing the validation batch size to <=2 might solve the issue, but I couldn't fully validate that either,

**Comment by stemper0123** [comment]
In my case, the error occurred when my custom dataset didn't start with an ID of 0 after converting it from RGB, resulting in an incorrect number of classes. 

To avoid this issue, it's imperative that you begin labeling your items from 0 and go up to n-1, where 'n' is the total number of classes. Any class falling outside this range could lead to the error.  This occurs because, after initializing the model with, say 15 classes, having a class with an ID of 16 in your output layer causes an out of bounds error.

**Comment by kongbai-account** [comment]
Thank you everyone. I've now found the reason. It's because my labels were resized, and after resizing, some pixels changed, causing the pixel values within the labels to exceed my number of classes.

**Comment by Andy718811** [comment]
您好，我想问你也是在训练前将自己的照片和彩色标签照片调整大小到960x720，然后你发现到彩色标签照片似乎在调整完大小后会使原先的色彩改变，对吗?

**Comment by kongbai-account** [comment]
彩色图片这个我没有去看过，好像没啥影响，我记得当时影响最大是.png的标签
